fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
api_notificationsetting:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Controller/UserController.php"